name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install http-server
        run: npm install -g http-server
        
      - name: Build & Prepare Files
        run: |
          mkdir -p output
          rsync -av --progress ./ ./output --exclude output --exclude .git --exclude .github


      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output  # The folder to deploy  

      - name: Start HTTP Server (Optional for testing)
        if: false
        run: http-server -p 8080 &
        
  deploy-to-gh-pages:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:    
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
      
